import turtle

def face():
    turtle.pensize(9)
    turtle.circle(200)
    turtle.left(90)
    turtle.penup()
    turtle.forward(250)
    turtle.left(90)
    turtle.forward(80)
    turtle.pensize(30)
    turtle.pendown()
    turtle.forward(0)
    turtle.left(180)
    turtle.penup()
    turtle.forward(160)
    turtle.pendown()
    turtle.forward(0)
    turtle.left(180)
    turtle.penup()
    turtle.pensize(10)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(190)
    turtle.left(90)
    turtle.forward(70)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(140)

face()

input()