import turtle
#turtle.forward(250)
#turtle.right(90)
#turtle.forward(250)
#turtle.right(90)
#turtle.forward(250)
#turtle.right(90)
#turtle.forward(250)
#input()
turtle.title("SUN")
turtle.shape("turtle")
turtle.fillcolor("yellow")
turtle.begin_fill()
for n in range(1,50):
    #turtle.forward(250)
    #turtle.right(90)
    turtle.pencolor("red")
    turtle.forward(50)
    turtle.right(75)
turtle.right(45)
turtle.forward(25)
turtle.end_fill()
input()